server:
  servlet:
    context-path: /api/diabetes-management
spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/diabetes-management
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

aws:
  access-key: ${AWS_ACCESS_KEY:}
  secret-key: ${AWS_SECRET_KEY:}
  region: us-east-1

app:
  file-upload:
    max-size: 10MB
    allowed-types: image/jpeg,image/png,application/pdf
    local-storage-path: ./uploads

fe:
  link: http://localhost:3000
